services:

  db:
    image: pgvector/pgvector:0.8.6-pg17-bookworm

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend
    command:
    - sh
    - -c
    - >
      uv run alembic upgrade head &&
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

    environment:
      APP_ENV: ${APP_ENV}
      TEXT_EMBEDDING_MODEL: ${TEXT_EMBEDDING_MODEL}
      TEXT_EMBEDDING_DIMENSION: ${TEXT_EMBEDDING_DIMENSION}
      TEXT_EMBEDDING_BATCH_SIZE: ${TEXT_EMBEDDING_BATCH_SIZE}
      TEXT_EMBEDDING_DEVICE: ${TEXT_EMBEDDING_DEVICE:-cuda}
      TEXT_QUERY_INSTRUCTION: ${TEXT_QUERY_INSTRUCTION}
      HNSW_EF_SEARCH: ${HNSW_EF_SEARCH}

      DATABASE_URL: >-
        postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      FRONTEND_ORIGIN: ${FRONTEND_ORIGIN}

      STORAGE_ROOT: /storage

      MAX_UPLOAD_SIZE_MB: ${MAX_UPLOAD_SIZE_MB:-25}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
  
    volumes:
    - ./storage:/storage
    - huggingface_cache:/root/.cache/huggingface

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/docs', timeout=2)"
        ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s


  frontend:
    build:
      context: ./frontend

    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

    ports:
      - "5173:5173"

    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data:
  huggingface_cache: