"""add visual language model analysis

Revision ID: 2bb2cf606454
Revises: bdd4c96e7c7a
Create Date: 2026-09-06 12:19:42.079756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bb2cf606454'
down_revision: Union[str, Sequence[str], None] = 'bdd4c96e7c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=False,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'english\'::regconfig, (COALESCE(heading, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(text, \'\'::text)), \'B\'::"char"))', persisted=True))
    op.drop_index(op.f('ix_document_chunks_search_vector_gin'), table_name='document_chunks', postgresql_using='gin')
    op.add_column('visual_assets', sa.Column('vlm_model', sa.String(length=255), nullable=True))
    op.add_column('visual_assets', sa.Column('vlm_prompt_version', sa.String(length=100), nullable=True))
    op.add_column('visual_assets', sa.Column('vlm_status', sa.String(length=50), nullable=True))
    op.add_column('visual_assets', sa.Column('vlm_error_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_visual_assets_vlm_status'), 'visual_assets', ['vlm_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_assets_vlm_status'), table_name='visual_assets')
    op.drop_column('visual_assets', 'vlm_error_message')
    op.drop_column('visual_assets', 'vlm_status')
    op.drop_column('visual_assets', 'vlm_prompt_version')
    op.drop_column('visual_assets', 'vlm_model')
    op.create_index(op.f('ix_document_chunks_search_vector_gin'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('document_chunks', 'search_vector',
               existing_type=postgresql.TSVECTOR(),
               nullable=True,
               existing_server_default=sa.Computed('(setweight(to_tsvector(\'english\'::regconfig, (COALESCE(heading, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, COALESCE(text, \'\'::text)), \'B\'::"char"))', persisted=True))
    # ### end Alembic commands ###
