"""support multimodal document ingestion

Revision ID: 989ba09aa63c
Revises: 9e9a216212f9
Create Date: 2026-09-03 18:19:36.717796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '989ba09aa63c'
down_revision: Union[str, Sequence[str], None] = '9e9a216212f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uq_kb_document_checksum', 'documents', ['knowledge_base_id', 'checksum_sha256'])
    op.add_column('visual_assets', sa.Column('mime_type', sa.String(length=150), nullable=True))
    op.add_column('visual_assets', sa.Column('checksum_sha256', sa.String(length=64), nullable=True))
    op.add_column('visual_assets', sa.Column('width_px', sa.Integer(), nullable=True))
    op.add_column('visual_assets', sa.Column('height_px', sa.Integer(), nullable=True))
    op.alter_column('visual_assets', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_visual_asset_location'), 'visual_assets', type_='unique')
    op.create_unique_constraint('uq_visual_asset_index', 'visual_assets', ['document_id', 'asset_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_visual_asset_index', 'visual_assets', type_='unique')
    op.create_unique_constraint(op.f('uq_visual_asset_location'), 'visual_assets', ['document_id', 'page_number', 'asset_index'], postgresql_nulls_not_distinct=False)
    op.alter_column('visual_assets', 'page_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('visual_assets', 'height_px')
    op.drop_column('visual_assets', 'width_px')
    op.drop_column('visual_assets', 'checksum_sha256')
    op.drop_column('visual_assets', 'mime_type')
    op.drop_constraint('uq_kb_document_checksum', 'documents', type_='unique')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'knowledge_bases', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
