"""add conversational memory

Revision ID: ba91e23863fd
Revises: 2bb2cf606454
Create Date: 2026-09-07 19:13:23.319911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba91e23863fd'
down_revision: Union[str, Sequence[str], None] = '2bb2cf606454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summarized_message_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summarized_message_count')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
