"""add visual embedding status columns

Revision ID: f231d7dfd63d
Revises: 28ec12dbae31
Create Date: 2026-09-05 11:18:06.373304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f231d7dfd63d'
down_revision: Union[str, Sequence[str], None] = '28ec12dbae31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('visual_assets', sa.Column('clip_pretrained', sa.String(length=255), nullable=True))
    op.add_column('visual_assets', sa.Column('clip_embedding_status', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_visual_assets_clip_embedding_hnsw'), table_name='visual_assets', postgresql_ops={'clip_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_visual_assets_clip_embedding_status'), 'visual_assets', ['clip_embedding_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_assets_clip_embedding_status'), table_name='visual_assets')
    op.create_index(op.f('ix_visual_assets_clip_embedding_hnsw'), 'visual_assets', ['clip_embedding'], unique=False, postgresql_ops={'clip_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('visual_assets', 'clip_embedding_status')
    op.drop_column('visual_assets', 'clip_pretrained')
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
